name: Test Secret

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Check Secret
      env:
        PPPOE_USER: ${{ secrets.PPPOE_USER }}
        ROOT_PASS: ${{ secrets.ROOT_PASS }}
        WIFI_KEY: ${{ secrets.WIFI_KEY }}
      run: |
        echo "PPPOE_USER LEN=${#PPPOE_USER}"
        echo "ROOT_PASS LEN=${#ROOT_PASS}"
        echo "WIFI_KEY LEN=${#WIFI_KEY}"

        sed -i "s|__ROOT_PASS__|$ROOT_PASS|g" files/etc/uci-defaults/99-setup

        grep ROOT_PASS files/etc/uci-defaults/99-setup
